{
 "title": "S.M.A.R.T",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disks Monitored",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(smartmon_device_active)" }
   ]
  },
  {
   "title": "Disk Drives",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    { "expr": "smartmon_device_info" }
   ]
  },
  {
   "title": "Unhealthy Disks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(smartmon_device_smart_enabled)-sum(smartmon_device_smart_healthy)"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature History",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"temperature_celsius\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Wear & Tear",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Power On Hours",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "h" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"power_on_hours\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Start Stop Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"start_stop_count\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Power Cycle Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"power_cycle_count\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Load Cycle Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"load_cycle_count\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Total Data Written",
     "type": "bargauge",
     "description": "Please note: This may be slightly incorrect",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"total_lbas_written\"}*512",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Reallocated Sector Events",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"reallocated_event_count\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raw Read Error",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_value{name=\"raw_read_error_rate\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Seek Error Rate",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_value{name=\"seek_error_rate\"}",
       "legendFormat": "{{ device }} {{disk }}"
      }
     ]
    },
    {
     "title": "Spin Retry Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"spin_retry_count\"}",
       "legendFormat": "{{ device }} {{ disk }}"
      }
     ]
    },
    {
     "title": "Command Timeout Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"command_timeout\"}",
       "legendFormat": "{{ device }} {{ disk }}"
      }
     ]
    },
    {
     "title": "Current Pending Sector Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"current_pending_sector\"}",
       "legendFormat": "{{ device }} {{ disk }}"
      }
     ]
    },
    {
     "title": "Offline Uncorrectable Sector Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"offline_uncorrectable\"}",
       "legendFormat": "{{ device }} {{ disk }}"
      }
     ]
    },
    {
     "title": "Reported Uncorrectable Errors",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"reported_uncorrect\"}",
       "legendFormat": "{{ device }} {{ disk }}"
      }
     ]
    },
    {
     "title": "UltraDMA CRC Error",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"udma_crc_error_count\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    }
   ]
  }
 ]
}