{
 "title": "Unbound Stats",
 "description": "Unbound DNS resolver metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(unbound_up, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Queries",
   "type": "stat",
   "description": "Total number of queries received at the selected time range.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(unbound_queries_total{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Queries per second",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(unbound_queries_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unwanted queries",
   "type": "stat",
   "description": "Total number of queries that were refused or dropped because they failed the access control settings at the selected time range.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(unbound_unwanted_queries_total{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Unwanted replies",
   "type": "stat",
   "description": "Total number of replies that were unwanted or unsolicited  at the selected time range.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(unbound_unwanted_replies_total{instance=\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Memory cache size",
   "type": "stat",
   "description": "Max memory in use by caches at the selected time range.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(unbound_memory_caches_bytes{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "description": "The number of threads created to serve clients",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(unbound_queries_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "heatmap",
   "description": "Query response time in seconds",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(unbound_response_time_seconds_bucket{instance=\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Cache hit/miss ratio",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(unbound_cache_hits_total{instance=\"$instance\"}[$__range]))",
     "legendFormat": "Hits"
    },
    {
     "expr": "sum(increase(unbound_cache_misses_total{instance=\"$instance\"}[$__range]))",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming TCP queries",
     "type": "stat",
     "description": "Total number of queries that were made using TCP towards the Unbound server at the selected time range.",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "increase(unbound_query_tcp_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Incoming TLS queries",
     "type": "stat",
     "description": "Total number of queries that were made using TLS towards the Unbound server at the selected time range.",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "increase(unbound_query_tls_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "IPv6 queries",
     "type": "stat",
     "description": "Total number of queries that were made using IPv6 towards the Unbound server at the selected time range.",
     "gridPos": { "h": 3, "w": 5, "x": 10, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "increase(unbound_query_ipv6_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Secure answers",
     "type": "stat",
     "description": "Total amount of answers that were secure (AD) at the selected time range.",
     "gridPos": { "h": 3, "w": 5, "x": 15, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "increase(unbound_answers_secure_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bogus answers",
     "type": "stat",
     "description": "Total amount of answers that were bogus (withheld as SERVFAIL) at the selected time range.",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "increase(unbound_answers_bogus{instance=\"$instance\"}[$__range])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "EDNS OPT queries",
     "type": "stat",
     "description": "Total number of queries that had an EDNS OPT record present at the selected time range.",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "increase(unbound_query_edns_present_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "EDNS OPT + DNSSEC OK queries",
     "type": "stat",
     "description": "Total number of queries that had an EDNS OPT record with the DO (DNSSEC OK) bit set present at the selected time range.",
     "gridPos": { "h": 3, "w": 5, "x": 10, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "increase(unbound_query_edns_DO_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total queries by type",
     "type": "timeseries",
     "description": "Total number of queries with a given query type",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(unbound_query_types_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Total answers by rcode",
     "type": "timeseries",
     "description": "Total number of answers by rcode",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(unbound_answer_rcodes_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{rcode}}"
      },
      {
       "expr": "rate(unbound_answers_secure_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Secure (AD)"
      },
      {
       "expr": "rate(unbound_answers_bogus{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "Bogus (SERVFAIL)"
      },
      {
       "expr": "rate(unbound_rrset_bogus_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "RRset bogus"
      }
     ]
    },
    {
     "title": "Total queries by flag",
     "type": "timeseries",
     "description": "Total number of queries that had a given flag set in the header",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(unbound_query_flags_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{flag}}"
      }
     ]
    },
    {
     "title": "Total queries by opcode",
     "type": "timeseries",
     "description": "Total number of queries with a given query opcode",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(unbound_query_opcodes_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{opcode}}"
      }
     ]
    },
    {
     "title": "Total queries by flag",
     "type": "timeseries",
     "description": "Total number of queries that had a given flag set in the header",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(unbound_query_classes_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{class}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Per thread",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total queries by thread",
     "type": "timeseries",
     "description": "Total number of queries handled by each worker thread",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(unbound_queries_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{thread}}"
      }
     ]
    },
    {
     "title": "Total cache prefetches by thread",
     "type": "timeseries",
     "description": "Total number of cache prefetches performed",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(unbound_prefetches_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{thread}}"
      }
     ]
    },
    {
     "title": "Total expired entries served by thread",
     "type": "timeseries",
     "description": "Total number of expired entries served",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(unbound_expired_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{thread}}"
      }
     ]
    },
    {
     "title": "Total recursive queries by thread",
     "type": "timeseries",
     "description": "Total number of queries that needed recursive processing",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "irate(unbound_recursive_replies_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{thread}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Request list",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request list size",
     "type": "timeseries",
     "description": "Current size of the request list, including internally generated queries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(unbound_request_list_current_all{instance=\"$instance\"})",
       "legendFormat": "all"
      },
      {
       "expr": "sum(unbound_request_list_current_user{instance=\"$instance\"})",
       "legendFormat": "user"
      }
     ]
    },
    {
     "title": "Total exceeded queries",
     "type": "timeseries",
     "description": "Number of queries that were dropped because the request list was full",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(unbound_request_list_exceeded_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Total overwritten queries",
     "type": "timeseries",
     "description": "Total number of requests in the request list that were overwritten by newer entries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(unbound_request_list_overwritten_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache hits / misses",
     "type": "timeseries",
     "description": "Hits: total number of queries that were successfully answered using a cache lookup.\n\nMisses: total number of cache queries that needed recursive processing",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(irate(unbound_cache_hits_total[$__rate_interval]))",
       "legendFormat": "Hits"
      },
      {
       "expr": "sum(irate(unbound_cache_misses_total[$__rate_interval]))",
       "legendFormat": "Misses"
      }
     ]
    },
    {
     "title": "Cache size",
     "type": "timeseries",
     "description": "Memory in bytes by caches",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "unbound_memory_caches_bytes{instance=\"$instance\"}",
       "legendFormat": "{{cache}}"
      }
     ]
    },
    {
     "title": "Cached entries",
     "type": "timeseries",
     "description": "The number of cached entries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "unbound_msg_cache_count{instance=\"$instance\"}",
       "legendFormat": "messages"
      },
      {
       "expr": "unbound_rrset_cache_count{instance=\"$instance\"}",
       "legendFormat": "rrset"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Modules size",
     "type": "timeseries",
     "description": "Memory in use by modules",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "unbound_memory_modules_bytes{instance=\"$instance\"}",
       "legendFormat": "{{module}}"
      }
     ]
    }
   ]
  }
 ]
}