{
 "title": "Bind9 Exporter",
 "tags": [
  "generated",
  "bind-exporter",
  "dns"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "label_values(bind_up, job)" },
   {
    "name": "instance",
    "query": "label_values(bind_up{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last Restarted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${__to:date:seconds} - max(bind_boot_time_seconds{job=\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Last Reconfigured",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${__to:date:seconds} - max(bind_config_time_seconds{job=\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Named CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_total{job=\"$job\",instance=\"$instance\"}[120s])",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_max_fds{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "process_open_fds{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Virtual"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Resident"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "increase(bind_query_duplicates_total{instance=\"$instance\",job=\"$job\"}[120s])",
     "legendFormat": "Duplicates"
    },
    {
     "expr": "increase(bind_query_errors_total{instance=\"$instance\",job=\"$job\"}[120s])",
     "legendFormat": "{{error}}"
    },
    {
     "expr": "increase(bind_query_recursions_total{instance=\"$instance\",job=\"$job\"}[120s])",
     "legendFormat": "Recursions"
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming Queries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "increase(bind_incoming_queries_total{instance=\"$instance\",job=\"$job\"}[120s])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Incoming Request Opcodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "increase(bind_incoming_requests_total{instance=\"$instance\",job=\"$job\"}[120s])",
       "legendFormat": "{{opcode}}"
      }
     ]
    },
    {
     "title": "Response Results",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "increase(bind_responses_total{instance=\"$instance\",job=\"$job\"}[120s])",
       "legendFormat": "{{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Zone",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Zone Serials",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "bind_zone_serial{instance=\"$instance\",job=\"$job\"}"
      }
     ]
    },
    {
     "title": "Zone Serial Changes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 38 },
     "targets": [
      {
       "expr": "rate(bind_zone_serial{instance=\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{zone_name}}"
      }
     ]
    },
    {
     "title": "Failed Zone Transfers",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "targets": [
      {
       "expr": "rate(bind_zone_transfer_failure_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Rejected Zone Transfers",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "expr": "rate(bind_zone_transfer_rejected_total{instance=\"$instance\",job=\"$job\"}[$__rate_interval])"
      }
     ]
    }
   ]
  }
 ]
}