{
 "title": "Blackbox Exporter Quick Overview",
 "tags": [
  "generated",
  "blackbox-exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Probes (Up/Down) - Current Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "targets": [
    { "expr": "probe_success" }
   ]
  },
  {
   "title": "Probes (Up/Down) - Historic Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "SSL Certificate Expiry",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry-time()"
    }
   ]
  },
  {
   "title": "DNS Lookup",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "probe_dns_lookup_time_seconds", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "probe_duration_seconds", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}