{
 "title": "Omada Controller Overview",
 "tags": [
  "generated",
  "omada-exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "device", "query": "omada_device_need_upgrade" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Controller Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "omada_controller_uptime_seconds"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "omada_client_connected_total" }
   ]
  },
  {
   "title": "Clients on 5GHz",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(omada_client_signal_dbm{wifi_mode=\"5\"})"
    }
   ]
  },
  {
   "title": "Clients on 2.4GHz",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(omada_client_signal_dbm{wifi_mode=\"4\"} or omada_client_signal_dbm{wifi_mode=\"2\"})"
    }
   ]
  },
  {
   "title": "Current Receive Rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(omada_device_rx_rate)" }
   ]
  },
  {
   "title": "Current Transmit Rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(omada_device_tx_rate)" }
   ]
  },
  {
   "title": "Client Download Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (client, ip) (omada_client_download_activity_bytes) > 0",
     "legendFormat": "{{client}} - {{ip}}"
    }
   ]
  },
  {
   "title": "Client Signal Strength",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "sum by (client, ip) (omada_client_signal_dbm)",
     "legendFormat": "{{client}} - {{ip}}"
    }
   ]
  },
  {
   "title": "$device",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "device",
   "collapsed": true,
   "panels": [
    {
     "title": "Device MAC Address",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "omada_device_need_upgrade{device=\"$device\"}"
      }
     ]
    },
    {
     "title": "Device Uptime",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "omada_device_uptime_seconds{device=\"$device\"}"
      }
     ]
    },
    {
     "title": "Connected Clients",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(omada_client_signal_dbm{ap_name=\"$device\"})"
      }
     ]
    },
    {
     "title": "Clients on 5GHz",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(omada_client_signal_dbm{ap_name=\"$device\",wifi_mode=\"5\"})"
      }
     ]
    },
    {
     "title": "Clients on 2.4GHz",
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(omada_client_signal_dbm{ap_name=\"$device\",wifi_mode=\"4\"} or omada_client_signal_dbm{ap_name=\"$device\",wifi_mode=\"2\"})"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "omada_device_cpu_percentage{device=\"$device\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "omada_device_mem_percentage{device=\"$device\"}",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "omada_device_rx_rate{device=\"$device\"}",
       "legendFormat": "{{device}} receive"
      },
      {
       "expr": "-omada_device_tx_rate{device=\"$device\"}",
       "legendFormat": "{{device}} transmit"
      }
     ]
    },
    {
     "title": "Client Signal Strength",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "sum by (client, ip) (omada_client_signal_dbm{ap_name=\"$device\"})",
       "legendFormat": "{{client}} - {{ip}}"
      }
     ]
    }
   ]
  }
 ]
}