{
 "title": "Power Usage Overview",
 "tags": [ "generated" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(homeassistant_sensor_voltage_v)"
    }
   ]
  },
  {
   "title": "Total Amps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(homeassistant_sensor_current_a)"
    }
   ]
  },
  {
   "title": "Total Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(homeassistant_sensor_power_w)"
    }
   ]
  },
  {
   "title": "Total Apparent Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(homeassistant_sensor_apparent_power_va)"
    }
   ]
  },
  {
   "title": "Total Reactive Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "voltampreact" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(homeassistant_sensor_reactive_power_var)"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "homeassistant_sensor_voltage_v", "legendFormat": "{{friendly_name}}" }
   ]
  },
  {
   "title": "Amps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "homeassistant_sensor_current_a", "legendFormat": "{{friendly_name}}" }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "homeassistant_sensor_power_w", "legendFormat": "{{friendly_name}}" }
   ]
  },
  {
   "title": "Power Factor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "homeassistant_sensor_power_factor_None",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Apparent Factor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_apparent_power_va",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Reactive Factor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "voltampreact" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_reactive_power_var",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  }
 ]
}