{
 "title": "S.M.A.R.T Status",
 "tags": [ "generated" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(node_exporter_build_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(node_exporter_build_info{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "host",
    "query": "label_values(node_exporter_build_info{cluster=~\"$cluster\", namespace=~\"$namespace\"}, host)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disks Monitored",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartmon_device_active{cluster=~\"$cluster\", namespace=~\"$namespace\", host=\"$host\"})"
    }
   ]
  },
  {
   "title": "Unhealthy Disks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartmon_device_smart_enabled{cluster=~\"$cluster\", namespace=~\"$namespace\", host=\"$host\"})-sum(smartmon_device_smart_healthy{cluster=~\"$cluster\", namespace=~\"$namespace\", host=\"$host\"})"
    }
   ]
  },
  {
   "title": "Disk Drives",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "smartmon_device_info{cluster=~\"$cluster\", namespace=~\"$namespace\", host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature History",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"temperature_celsius\",cluster=~\"$cluster\", namespace=~\"$namespace\", host=\"$host\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Wear & Tear",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Power On Hours",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "h" } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"power_on_hours\",cluster=~\"$cluster\", namespace=~\"$namespace\", host=\"$host\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Start Stop Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"start_stop_count\",cluster=~\"$cluster\", namespace=~\"$namespace\", host=\"$host\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Power Cycle Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"power_cycle_count\",cluster=~\"$cluster\", namespace=~\"$namespace\", host=\"$host\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Load Cycle Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"load_cycle_count\",cluster=~\"$cluster\", namespace=~\"$namespace\", host=\"$host\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Total Data Written",
     "type": "bargauge",
     "description": "Please note: This may be slightly incorrect",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"total_lbas_written\",cluster=~\"$cluster\", namespace=~\"$namespace\", host=\"$host\"}*512",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Reasslocated Sector Events",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"reallocated_event_count\",cluster=~\"$cluster\", namespace=~\"$namespace\", host=\"$host\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raw Read Error",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "smartmon_attr_value{name=\"raw_read_error_rate\",cluster=~\"$cluster\", namespace=~\"$namespace\", host=\"$host\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Seek Error Rate",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "smartmon_attr_value{name=\"seek_error_rate\",cluster=~\"$cluster\", namespace=~\"$namespace\", host=\"$host\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Spin Retry Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"spin_retry_count\",cluster=~\"$cluster\", namespace=~\"$namespace\", host=\"$host\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Command Timeout Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"command_timeout\",cluster=~\"$cluster\", namespace=~\"$namespace\", host=\"$host\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Current Pending Sector Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"current_pending_sector\",cluster=~\"$cluster\", namespace=~\"$namespace\", host=\"$host\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Offline Uncorrectable Sector Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"offline_uncorrectable\",cluster=~\"$cluster\", namespace=~\"$namespace\", host=\"$host\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Reported Uncorrectable Errors",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"reported_uncorrect\",cluster=~\"$cluster\", namespace=~\"$namespace\", host=\"$host\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "UltraDMA CRC Error",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{name=\"udma_crc_error_count\",cluster=~\"$cluster\", namespace=~\"$namespace\", host=\"$host\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    }
   ]
  }
 ]
}