{
 "title": "SNMP Interface Status",
 "tags": [
  "generated",
  "snmp-exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(ifOperStatus, instance)"
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": "label_values(ifOperStatus{instance=\"$instance\"}, ifDescr)"
   }
  ]
 },
 "panels": [
  {
   "title": "Admin Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifAdminStatus{instance=\"$instance\",ifDescr=\"$interface\"}"
    }
   ]
  },
  {
   "title": "Oper Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifOperStatus{instance=\"$instance\",ifDescr=\"$interface\"}"
    }
   ]
  },
  {
   "title": "Last Change",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance=\"$instance\"} - on(instance) ifLastChange{instance=\"$instance\",ifDescr=\"$interface\"}"
    }
   ]
  },
  {
   "title": "Connector Present",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifConnectorPresent{instance=\"$instance\",ifDescr=\"$interface\"}"
    }
   ]
  },
  {
   "title": "Promiscuous Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifPromiscuousMode{instance=\"$instance\",ifDescr=\"$interface\"}"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifHighSpeed{instance=\"$instance\",ifDescr=\"$interface\"}*1000000 or ifSpeed{instance=\"$instance\",ifDescr=\"$interface\"}"
    }
   ]
  },
  {
   "title": "MTU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifMtu{instance=\"$instance\",ifDescr=\"$interface\"}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "ifType_info{instance=\"$instance\",ifDescr=\"$interface\"}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(rate(ifHCInOctets{instance=\"$instance\",ifDescr=\"$interface\"}[$__rate_interval]) or rate(ifInOctets{instance=\"$instance\",ifDescr=\"$interface\"}[$__rate_interval]))*8",
     "legendFormat": "IN: {{ifDescr}}"
    },
    {
     "expr": "(rate(ifHCOutOctets{instance=\"$instance\",ifDescr=\"$interface\"}[$__rate_interval]) or rate(ifOutOctets{instance=\"$instance\",ifDescr=\"$interface\"}[$__rate_interval]))*8",
     "legendFormat": "OUT: {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Broadcast Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "(rate(ifHCInBroadcastPkts{instance=\"$instance\",ifDescr=\"$interface\"}[$__rate_interval]) or rate(ifInBroadcastPkts{instance=\"$instance\",ifDescr=\"$interface\"}[$__rate_interval]))",
     "legendFormat": "IN: {{ifDescr}}"
    },
    {
     "expr": "(rate(ifHCOutBroadcastPkts{instance=\"$instance\",ifDescr=\"$interface\"}[$__rate_interval]) or rate(ifOutBroadcastPkts{instance=\"$instance\",ifDescr=\"$interface\"}[$__rate_interval]))",
     "legendFormat": "OUT: {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Unicast Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "(rate(ifHCInUcastPkts{instance=\"$instance\",ifDescr=\"$interface\"}[$__rate_interval]) or rate(ifInUcastPkts{instance=\"$instance\",ifDescr=\"$interface\"}[$__rate_interval]))*8",
     "legendFormat": "IN: {{ifDescr}}"
    },
    {
     "expr": "(rate(ifHCOutUcastPkts{instance=\"$instance\",ifDescr=\"$interface\"}[$__rate_interval]) or rate(ifOutUcastPkts{instance=\"$instance\",ifDescr=\"$interface\"}[$__rate_interval]))*8",
     "legendFormat": "OUT: {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Multicast Packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "(rate(ifHCInMulticastPkts{instance=\"$instance\",ifDescr=\"$interface\"}[$__rate_interval]) or rate(ifInMulticastPkts{instance=\"$instance\",ifDescr=\"$interface\"}[$__rate_interval]))*8",
     "legendFormat": "IN: {{ifDescr}}"
    },
    {
     "expr": "(rate(ifHCOutMulticastPkts{instance=\"$instance\",ifDescr=\"$interface\"}[$__rate_interval]) or rate(ifOutMulticastPkts{instance=\"$instance\",ifDescr=\"$interface\"}[$__rate_interval]))*8",
     "legendFormat": "OUT: {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifInErrors{instance=\"$instance\",ifDescr=\"$interface\"}[$__rate_interval])",
     "legendFormat": "IN: {{ifDescr}}"
    },
    {
     "expr": "rate(ifOutErrors{instance=\"$instance\",ifDescr=\"$interface\"}[$__rate_interval])",
     "legendFormat": "OUT: {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Discards",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifInDiscards{instance=\"$instance\",ifDescr=\"$interface\"}[$__rate_interval])",
     "legendFormat": "IN discards: {{ifDescr}}"
    },
    {
     "expr": "rate(ifInUnknownProtos{instance=\"$instance\",ifDescr=\"$interface\"}[$__rate_interval])",
     "legendFormat": "IN unknown protos: {{ifDescr}}"
    },
    {
     "expr": "rate(ifOutDiscards{instance=\"$instance\",ifDescr=\"$interface\"}[$__rate_interval])",
     "legendFormat": "OUT discards: {{ifDescr}}"
    }
   ]
  }
 ]
}