{
 "title": "Bind9 Exporter DNS",
 "description": "Bind9 DNS Service Statistics.",
 "tags": [
  "bind",
  "dns",
  "bind-exporter",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(bind_up, job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(bind_up{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Restarted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "${__to:date:seconds} - max(bind_boot_time_seconds{job=\"$job\"}) "
    }
   ]
  },
  {
   "title": "Reconfigured",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "${__to:date:seconds} - max(bind_config_time_seconds{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Named CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_total{job=\"$job\",instance=\"$instance\"}[120s])"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_max_fds{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "process_open_fds{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Virtual"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Resident"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bind_query_duplicates_total{instance=\"$instance\",job=\"$job\"}[120s])",
     "legendFormat": "Duplicates"
    },
    {
     "expr": "increase(bind_query_errors_total{instance=\"$instance\",job=\"$job\"}[120s])",
     "legendFormat": "{{ error }}"
    },
    {
     "expr": "increase(bind_query_recursions_total{instance=\"$instance\",job=\"$job\"}[120s])",
     "legendFormat": "Recursions"
    }
   ]
  },
  {
   "title": "Incoming",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Incoming Queries",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(bind_incoming_queries_total{instance=\"$instance\",job=\"$job\"}[120s])",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Incoming Request Opcodes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(bind_incoming_requests_total{instance=\"$instance\",job=\"$job\"}[120s])",
       "legendFormat": "{{ opcode }}"
      }
     ]
    },
    {
     "title": "Response Results",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(bind_responses_total{instance=\"$instance\",job=\"$job\"}[120s])",
       "legendFormat": "{{ result }}"
      }
     ]
    }
   ]
  },
  { "title": "Zone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Zone Serials",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "bind_zone_serial{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zone Serial Changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "rate(bind_zone_serial{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{zone_name}}"
    }
   ]
  },
  {
   "title": "Failed Zone Transfers",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "rate(bind_zone_transfer_failure_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rejected Zone Transfers",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "rate(bind_zone_transfer_rejected_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}