{
 "title": "UPS Status",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "UPS State",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ups_state", "legendFormat": "{{ device}}" }
   ]
  },
  {
   "title": "UPS State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "targets": [
    { "expr": "ups_state", "legendFormat": "{{ device}}" }
   ]
  },
  {
   "title": "UPS Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "ups_in_voltage", "legendFormat": "{{ device }}" }
   ]
  },
  {
   "title": "Battery Capacity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ups_battery_capacity", "legendFormat": "{{ device }}" }
   ]
  },
  {
   "title": "Battery Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "ups_battery_capacity", "legendFormat": "{{ device }}" }
   ]
  },
  {
   "title": "UPS Output Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "ups_out_voltage", "legendFormat": "{{ device }}" }
   ]
  },
  {
   "title": "Battery Time Remaining",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ups_runtime_remaining", "legendFormat": "{{ device }}" }
   ]
  },
  {
   "title": "Battery Time Remaining",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    { "expr": "ups_runtime_remaining", "legendFormat": "{{ device }}" }
   ]
  },
  {
   "title": "UPS Load ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "ups_load", "legendFormat": "{{device}}" }
   ]
  }
 ]
}