{
 "title": "Agent Prometheus Remote Write",
 "tags": [ "grafana-agent" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(agent_build_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(agent_build_info{cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(agent_build_info{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Timestamps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Highest Timestamp In vs. Highest Timestamp Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "prometheus_remote_storage_highest_timestamp_in_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\", instance=~\"$instance\"} - ignoring(url, remote_name) group_right(cluster, namespace, instance) prometheus_remote_storage_queue_highest_sent_timestamp_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\", instance=~\"$instance\"}",
     "legendFormat": "{{cluster}}:{{namespace}}:{{instance}}-{{instance_group_name}}-{{url}}"
    }
   ]
  },
  {
   "title": "Latency [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(prometheus_remote_storage_sent_batch_duration_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\", instance=~\"$instance\"}[1m]) / rate(prometheus_remote_storage_sent_batch_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\", instance=~\"$instance\"}[1m])",
     "legendFormat": "mean {{cluster}}:{{namespace}}:{{instance}}-{{instance_group_name}}-{{url}}"
    },
    {
     "expr": "histogram_quantile(0.99, rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "p99 {{cluster}}:{{namespace}}:{{instance}}-{{instance_group_name}}-{{url}}"
    }
   ]
  },
  {
   "title": "Samples",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate in [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "rate(agent_wal_samples_appended_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\", instance=~\"$instance\"}[5m])",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}}-{{instance_group_name}}"
      }
     ]
    },
    {
     "title": "Rate succeeded [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_samples_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\", instance=~\"$instance\"}[5m])",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}}-{{instance_group_name}}-{{url}}"
      }
     ]
    },
    {
     "title": "Pending Samples",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "prometheus_remote_storage_samples_pending{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\", instance=~\"$instance\"}",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}}-{{instance_group_name}}-{{url}}"
      }
     ]
    },
    {
     "title": "Dropped Samples [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_samples_dropped_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\", instance=~\"$instance\"}[5m])",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}}-{{instance_group_name}}-{{url}}"
      }
     ]
    },
    {
     "title": "Failed Samples [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_samples_failed_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\", instance=~\"$instance\"}[5m])",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}}-{{instance_group_name}}-{{url}}"
      }
     ]
    },
    {
     "title": "Retried Samples [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_samples_retried_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\", instance=~\"$instance\"}[5m])",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}}-{{instance_group_name}}-{{url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Shards",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "prometheus_remote_storage_shards{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\", instance=~\"$instance\"}",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}}-{{instance_group_name}}-{{url}}"
      }
     ]
    },
    {
     "title": "Max Shards",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "prometheus_remote_storage_shards_max{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\", instance=~\"$instance\"}",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}}-{{instance_group_name}}-{{url}}"
      }
     ]
    },
    {
     "title": "Min Shards",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "prometheus_remote_storage_shards_min{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\", instance=~\"$instance\"}",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}}-{{instance_group_name}}-{{url}}"
      }
     ]
    },
    {
     "title": "Desired Shards",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "prometheus_remote_storage_shards_desired{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\", instance=~\"$instance\"}",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}}-{{instance_group_name}}-{{url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Shard Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shard Capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "prometheus_remote_storage_shard_capacity{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\", instance=~\"$instance\"}",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}}-{{instance_group_name}}-{{url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Remote Write Current Segment",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "prometheus_wal_watcher_current_segment{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\", instance=~\"$instance\"}",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}}-{{instance_group_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc. Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Enqueue Retries [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_enqueue_retries_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\", instance=~\"$instance\"}[5m])",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}}-{{instance_group_name}}-{{url}}"
      }
     ]
    }
   ]
  }
 ]
}