{
 "title": "Agent / Logs Pipeline",
 "tags": [
  "generated",
  "grafana-agent"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(agent_build_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(agent_build_info{cluster=~\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dropped bytes rate [B/s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(promtail_dropped_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"}[$__rate_interval]))\n",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Write requests success rate [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(promtail_request_duration_seconds_bucket{status_code=~\"2..\", cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"}[$__rate_interval]))\n/\nsum by(instance) (rate(promtail_request_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"}[$__rate_interval]))\n* 100\n",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Write latencies p99 [s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, instance) (rate(promtail_request_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"}[$__rate_interval]))\n)\n",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Write latencies p90 [s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le, instance) (rate(promtail_request_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"}[$__rate_interval]))\n)\n",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Write latencies p50 [s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, instance) (rate(promtail_request_duration_seconds_bucket{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"}[$__rate_interval]))\n)\n",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Write latencies average [s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (le, instance) (rate(promtail_request_duration_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"}[$__rate_interval])))\n/\n(sum by (le, instance) (rate(promtail_request_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"}[$__rate_interval])))\n",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Logs volume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Bytes read rate [B/s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(promtail_read_bytes_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"}[$__rate_interval]))\n",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Lines read rate [lines/s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(promtail_read_lines_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"}[$__rate_interval]))\n",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Active files count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by(instance) (promtail_files_active_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"})\n",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Entries sent rate [entries/s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(promtail_sent_entries_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"}[$__rate_interval]))\n",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}