{
 "title": "Bind Overview",
 "tags": [
  "generated",
  "bind"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "cluster", "query": "label_values(bind_up, cluster)" },
   {
    "name": "namespace",
    "query": "label_values(bind_up{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "host",
    "query": "label_values(bind_up{cluster=~\"$cluster\", namespace=~\"$namespace\"}, host)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All DNS Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(irate(bind_incoming_queries_total{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "Incoming"
    },
    {
     "expr": "sum(irate(bind_resolver_queries_total{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "Outgoing"
    }
   ]
  },
  {
   "title": "Incoming DNS Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "irate(bind_incoming_queries_total{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\"}[$__rate_interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Outgoing DNS Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "irate(bind_resolver_queries_total{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\"}[$__rate_interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Incoming Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "irate(bind_incoming_requests_total{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\"}[$__rate_interval])",
     "legendFormat": "{{ opcode }}"
    }
   ]
  },
  {
   "title": "Responses Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "irate(bind_responses_total{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\"}[$__rate_interval])",
     "legendFormat": "{{ result }}"
    }
   ]
  },
  {
   "title": "Last Restarted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bind_boot_time_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\"} * 1000"
    }
   ]
  },
  {
   "title": "Last Reconfigured",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bind_config_time_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\"} * 1000"
    }
   ]
  },
  {
   "title": "Issues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resolver Query Retries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "irate(bind_resolver_query_retries_total{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\"}[$__rate_interval])",
       "legendFormat": "queries retried {{ view }}"
      }
     ]
    },
    {
     "title": "Query Issues",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "targets": [
      {
       "expr": "irate(bind_query_duplicates_total{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\"}[$__rate_interval])",
       "legendFormat": "Duplicated queries received"
      },
      {
       "expr": "irate(bind_query_errors_total{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ error }} queries"
      },
      {
       "expr": "irate(bind_query_recursions_total{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\"}[$__rate_interval])",
       "legendFormat": "Queries causing recursionries received"
      }
     ]
    },
    {
     "title": "Resolver Response Errors Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "irate(bind_resolver_response_errors_total{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ error }} {{ view }}"
      }
     ]
    },
    {
     "title": "Resolver Queries Failed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "irate(bind_resolver_query_errors_total{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ error }} {{ view }}"
      },
      {
       "expr": "irate(bind_resolver_query_edns0_errors_total{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\"}[$__rate_interval])",
       "legendFormat": "EDNS(0) error {{ view }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Zones",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Zone Serials",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "bind_zone_serial{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\"}"
      }
     ]
    },
    {
     "title": "Zone Serial Changes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "targets": [
      {
       "expr": "rate(bind_zone_serial{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\"}[$__rate_interval])",
       "legendFormat": "{{ zone_name }}"
      }
     ]
    },
    {
     "title": "Failed Zone Transfers",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "rate(bind_zone_transfer_failure_total{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\"}[$__rate_interval])",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Rejected Zone Transfers",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "rate(bind_zone_transfer_rejected_total{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\"}[$__rate_interval])",
       "legendFormat": " "
      }
     ]
    }
   ]
  }
 ]
}