{
 "title": "Blackbox Exporter Overview",
 "tags": [
  "generated",
  "blackbox_exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(probe_success, cluster)"
   },
   {
    "name": "job",
    "query": "label_values(probe_success{cluster=~\"$cluster\"}, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Probes (Up/Down) - Current Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{cluster=~\"$cluster\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Probes (Up/Down) - Historic Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{cluster=~\"$cluster\", job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SSL Certificate Expiry",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{cluster=~\"$cluster\", job=~\"$job\"} - time()"
    }
   ]
  },
  {
   "title": "DNS Lookup",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{cluster=~\"$cluster\", job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{cluster=~\"$cluster\", job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}