{
 "title": "Dnsmasq Overview",
 "tags": [
  "generated",
  "dnsmasq"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(dnsmasq_exporter_build_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(dnsmasq_exporter_build_info{cluster=~\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Upstream Queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dnsmasq_servers_queries{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"($namespace)/dnsmasq_exporter\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Failed Upstream Queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dnsmasq_servers_queries_failed{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"($namespace)/dnsmasq_exporter\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Percentage of Failed Upstream Queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(dnsmasq_servers_queries_failed{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"($namespace)/dnsmasq_exporter\"}) / sum(dnsmasq_servers_queries{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"($namespace)/dnsmasq_exporter\"})"
    }
   ]
  },
  {
   "title": "Upstream Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(dnsmasq_servers_queries{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"($namespace)/dnsmasq_exporter\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Failed Upstream Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(dnsmasq_servers_queries_failed{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"($namespace)/dnsmasq_exporter\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(dnsmasq_hits{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"($namespace)/dnsmasq_exporter\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(dnsmasq_misses{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"($namespace)/dnsmasq_exporter\"}[$__rate_interval])"
    }
   ]
  }
 ]
}