{
 "title": "Prometheus / Remote Write",
 "tags": [
  "generated",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(prometheus_build_info, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(prometheus_build_info{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "url",
    "query": "label_values(prometheus_remote_storage_shards{cluster=~\"$cluster\", namespace=~\"$namespace\"}, url)"
   }
  ]
 },
 "panels": [
  { "title": "Timestamps", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Highest Timestamp In vs. Highest Timestamp Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(\n  prometheus_remote_storage_highest_timestamp_in_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\"}\n-\n  ignoring(remote_name, url) group_right(cluster, namespace, instance) (prometheus_remote_storage_queue_highest_sent_timestamp_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", url=~\"$url\"} != 0)\n)\n",
     "legendFormat": "{{cluster}}:{{namespace}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Rate[5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "clamp_min(\n  rate(prometheus_remote_storage_highest_timestamp_in_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\"}[5m])\n-\n  ignoring (remote_name, url) group_right(cluster, namespace, instance) rate(prometheus_remote_storage_queue_highest_sent_timestamp_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", url=~\"$url\"}[5m])\n, 0)\n",
     "legendFormat": "{{cluster}}:{{namespace}}:{{instance}} {{remote_name}}:{{url}}"
    }
   ]
  },
  {
   "title": "Samples",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 24, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate, in vs. succeeded or dropped [5m]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "(\n  rate(prometheus_remote_storage_samples_in_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\"}[5m])\n-\n  ignoring(remote_name, url) group_right(cluster, namespace, instance) (rate(prometheus_remote_storage_succeeded_samples_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", url=~\"$url\"}[5m]) or rate(prometheus_remote_storage_samples_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", url=~\"$url\"}[5m]))\n-\n  (rate(prometheus_remote_storage_dropped_samples_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", url=~\"$url\"}[5m]) or rate(prometheus_remote_storage_samples_dropped_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", url=~\"$url\"}[5m]))\n)\n",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}} {{remote_name}}:{{url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Shards",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "prometheus_remote_storage_shards{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", url=~\"$url\"}",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}} {{remote_name}}:{{url}}"
      }
     ]
    },
    {
     "title": "Max Shards",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "prometheus_remote_storage_shards_max{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", url=~\"$url\"}",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}} {{remote_name}}:{{url}}"
      }
     ]
    },
    {
     "title": "Min Shards",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "targets": [
      {
       "expr": "prometheus_remote_storage_shards_min{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", url=~\"$url\"}",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}} {{remote_name}}:{{url}}"
      }
     ]
    },
    {
     "title": "Desired Shards",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
     "targets": [
      {
       "expr": "prometheus_remote_storage_shards_desired{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", url=~\"$url\"}",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}} {{remote_name}}:{{url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Shard Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shard Capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "prometheus_remote_storage_shard_capacity{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", url=~\"$url\"}",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}} {{remote_name}}:{{url}}"
      }
     ]
    },
    {
     "title": "Pending Samples",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "targets": [
      {
       "expr": "prometheus_remote_storage_pending_samples{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", url=~\"$url\"} or prometheus_remote_storage_samples_pending{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", url=~\"$url\"}",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}} {{remote_name}}:{{url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "TSDB Current Segment",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "prometheus_tsdb_wal_segment_current{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\"}",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}}"
      }
     ]
    },
    {
     "title": "Remote Write Current Segment",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "targets": [
      {
       "expr": "prometheus_wal_watcher_current_segment{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\"}",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}} {{consumer}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc. Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dropped Samples",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_dropped_samples_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", url=~\"$url\"}[5m]) or rate(prometheus_remote_storage_samples_dropped_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", url=~\"$url\"}[5m])",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}} {{remote_name}}:{{url}}"
      }
     ]
    },
    {
     "title": "Failed Samples",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_failed_samples_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", url=~\"$url\"}[5m]) or rate(prometheus_remote_storage_samples_failed_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", url=~\"$url\"}[5m])",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}} {{remote_name}}:{{url}}"
      }
     ]
    },
    {
     "title": "Retried Samples",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_retried_samples_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", url=~\"$url\"}[5m]) or rate(prometheus_remote_storage_samples_retried_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", url=~\"$url\"}[5m])",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}} {{remote_name}}:{{url}}"
      }
     ]
    },
    {
     "title": "Enqueue Retries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_enqueue_retries_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", url=~\"$url\"}[5m])",
       "legendFormat": "{{cluster}}:{{namespace}}:{{instance}} {{remote_name}}:{{url}}"
      }
     ]
    }
   ]
  }
 ]
}