{
 "title": "SMART Overview",
 "tags": [
  "generated",
  "smart"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(smartmon_smartctl_version, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(smartmon_smartctl_version{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "host",
    "query": "label_values(smartmon_smartctl_version{cluster=~\"$cluster\", namespace=~\"$namespace\"}, host)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disks Monitored",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartmon_device_active{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Disk Drives",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "smartmon_device_info{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Unhealthy Disks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartmon_device_smart_enabled{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\"})-sum(smartmon_device_smart_healthy{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 4, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature History",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\", name=\"temperature_celsius\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Wear & Tear",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Power On Hours",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "h" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\", name=\"power_on_hours\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Start Stop Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\", name=\"start_stop_count\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Power Cycle Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\", name=\"power_cycle_count\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Load Cycle Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\", name=\"load_cycle_count\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Total Data Written",
     "type": "bargauge",
     "description": "Please note: This may be slightly incorrect",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\", name=\"total_lbas_written\"} * 512",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Reallocated Sector Events",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\", name=\"reallocated_event_count\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raw Read Error",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_value{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\", name=\"raw_read_error_rate\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Seek Error Rate",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_value{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\", name=\"seek_error_rate\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Spin Retry Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\", name=\"spin_retry_count\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Command Timeout Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\", name=\"command_timeout\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Current Pending Sector Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\", name=\"current_pending_sector\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Offline Uncorrectable Sector Count",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\", name=\"offline_uncorrectable\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "Reported Uncorrectable Errors",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\", name=\"reported_uncorrect\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    },
    {
     "title": "UltraDMA CRC Error",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "smartmon_attr_raw_value{cluster=~\"$cluster\", namespace=~\"$namespace\", host=~\"$host\", name=\"udma_crc_error_count\"}",
       "legendFormat": "{{device}} {{disk}}"
      }
     ]
    }
   ]
  }
 ]
}