{
 "title": "SNMP Interface Status",
 "tags": [
  "generated",
  "snmp"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(ifOperStatus, cluster)"
   },
   {
    "name": "instance",
    "query": "label_values(ifOperStatus{cluster=\"$cluster\"}, instance)"
   },
   {
    "name": "interface",
    "query": "label_values(ifOperStatus{cluster=\"$cluster\", instance=\"$instance\"}, ifDescr)"
   }
  ]
 },
 "panels": [
  {
   "title": "Admin Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifAdminStatus{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}"
    }
   ]
  },
  {
   "title": "Oper Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifOperStatus{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}"
    }
   ]
  },
  {
   "title": "Last Change",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{cluster=\"$cluster\", instance=\"$instance\"} - on(cluster, instance) ifLastChange{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}"
    }
   ]
  },
  {
   "title": "Connector Present",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifConnectorPresent{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}"
    }
   ]
  },
  {
   "title": "Promiscuous Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifPromiscuousMode{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifHighSpeed{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"} * 1000000 or ifSpeed{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}"
    }
   ]
  },
  {
   "title": "MTU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifMtu{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "ifType_info{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(rate(ifHCInOctets{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}[$__rate_interval]) or rate(ifInOctets{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}[$__rate_interval])) * 8",
     "legendFormat": "IN: {{ifDescr}}"
    },
    {
     "expr": "(rate(ifHCOutOctets{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}[$__rate_interval]) or rate(ifOutOctets{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}[$__rate_interval])) * 8",
     "legendFormat": "OUT: {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Broadcast Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "(rate(ifHCInBroadcastPkts{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}[$__rate_interval]) or rate(ifInBroadcastPkts{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}[$__rate_interval]))",
     "legendFormat": "IN: {{ifDescr}}"
    },
    {
     "expr": "(rate(ifHCOutBroadcastPkts{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}[$__rate_interval]) or rate(ifOutBroadcastPkts{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}[$__rate_interval]))",
     "legendFormat": "OUT: {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Unicast Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "(rate(ifHCInUcastPkts{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}[$__rate_interval]) or rate(ifInUcastPkts{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}[$__rate_interval]))",
     "legendFormat": "IN: {{ifDescr}}"
    },
    {
     "expr": "(rate(ifHCOutUcastPkts{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}[$__rate_interval]) or rate(ifOutUcastPkts{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}[$__rate_interval]))",
     "legendFormat": "OUT: {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Multicast Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "(rate(ifHCInMulticastPkts{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}[$__rate_interval]) or rate(ifInMulticastPkts{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}[$__rate_interval]))",
     "legendFormat": "IN: {{ifDescr}}"
    },
    {
     "expr": "(rate(ifHCOutMulticastPkts{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}[$__rate_interval]) or rate(ifOutMulticastPkts{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}[$__rate_interval]))",
     "legendFormat": "OUT: {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifInErrors{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}[$__rate_interval])",
     "legendFormat": "IN: {{ifDescr}}"
    },
    {
     "expr": "rate(ifOutErrors{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}[$__rate_interval])",
     "legendFormat": "OUT: {{ifDescr}}"
    }
   ]
  },
  {
   "title": "Discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifInDiscards{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}[$__rate_interval])",
     "legendFormat": "IN discards: {{ifDescr}}"
    },
    {
     "expr": "rate(ifInUnknownProtos{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}[$__rate_interval])",
     "legendFormat": "IN unknown protos: {{ifDescr}}"
    },
    {
     "expr": "rate(ifOutDiscards{cluster=\"$cluster\", instance=\"$instance\", ifDescr=\"$interface\"}[$__rate_interval])",
     "legendFormat": "OUT discards: {{ifDescr}}"
    }
   ]
  }
 ]
}