{
 "title": "Agent",
 "tags": [ "grafana-agent" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(agent_build_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(agent_build_info{cluster=~\"$cluster\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Agent Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Agent Stats",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count by (cluster, namespace, instance, version) (agent_build_info{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster, namespace, instance) (time() - process_start_time_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus Discovery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Target Sync",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"}[$__rate_interval])) by (instance, scrape_job) * 1e3",
       "legendFormat": "{{instance}} {{scrape_job}}"
      }
     ]
    },
    {
     "title": "Targets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum by (instance) (prometheus_sd_discovered_targets{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Prometheus Retrieval",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Scrape Interval Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(prometheus_target_interval_length_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"}[$__rate_interval])\r\n    /\r\nrate(prometheus_target_interval_length_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"}[$__rate_interval])\r\n    * 1e3",
       "legendFormat": "{{instance}} {{interval}} configured"
      }
     ]
    },
    {
     "title": "Scrape failures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum by (job) (rate(prometheus_target_scrapes_exceeded_sample_limit_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"}[$__rate_interval]))",
       "legendFormat": "exceeded sample limit: {{job}}"
      },
      {
       "expr": "sum by (job) (rate(prometheus_target_scrapes_sample_duplicate_timestamp_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"}[$__rate_interval]))",
       "legendFormat": "duplicate timestamp: {{job}}"
      },
      {
       "expr": "sum by (job) (rate(prometheus_target_scrapes_sample_out_of_bounds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"}[$__rate_interval]))",
       "legendFormat": "out of bounds: {{job}}"
      },
      {
       "expr": "sum by (job) (rate(prometheus_target_scrapes_sample_out_of_order_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"}[$__rate_interval]))",
       "legendFormat": "out of order: {{job}}"
      }
     ]
    },
    {
     "title": "Appended Samples",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum by (job, instance_group_name) (rate(agent_wal_samples_appended_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/agent\"}[$__rate_interval]))",
       "legendFormat": "{{job}} {{instance_group_name}}"
      }
     ]
    }
   ]
  }
 ]
}