{
 "title": "Prometheus / Overview",
 "tags": [ "prometheus" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(prometheus_build_info,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(prometheus_build_info{cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(prometheus_build_info{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Prometheus Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus Stats",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count by (cluster, namespace, instance, version) (prometheus_build_info{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster, namespace, instance) (time() - process_start_time_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discovery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Target Sync",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", instance=~\"$instance\"}[$__rate_interval])) by (scrape_job) * 1e3",
       "legendFormat": "{{scrape_job}}"
      }
     ]
    },
    {
     "title": "Targets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(prometheus_sd_discovered_targets{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", instance=~\"$instance\"})",
       "legendFormat": "Targets"
      }
     ]
    }
   ]
  },
  {
   "title": "Retrieval",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Scrape Interval Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(prometheus_target_interval_length_seconds_sum{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", instance=~\"$instance\"}[$__rate_interval])\r\n    /\r\nrate(prometheus_target_interval_length_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", instance=~\"$instance\"}[$__rate_interval])\r\n    * 1e3",
       "legendFormat": "{{namespace}}:{{instance}} {{interval}} configured"
      }
     ]
    },
    {
     "title": "Scrape failures",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "sum by (job) (rate(prometheus_target_scrapes_exceeded_body_size_limit_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "exceeded body size limit: {{job}}"
      },
      {
       "expr": "sum by (job) (rate(prometheus_target_scrapes_exceeded_sample_limit_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "exceeded sample limit: {{job}}"
      },
      {
       "expr": "sum by (job) (rate(prometheus_target_scrapes_sample_duplicate_timestamp_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "duplicate timestamp: {{job}}"
      },
      {
       "expr": "sum by (job) (rate(prometheus_target_scrapes_sample_out_of_bounds_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "out of bounds: {{job}}"
      },
      {
       "expr": "sum by (job) (rate(prometheus_target_scrapes_sample_out_of_order_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "out of order: {{job}}"
      }
     ]
    },
    {
     "title": "Appended Samples",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_samples_appended_total{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{job}} {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Head Series",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_series{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", instance=~\"$instance\"}",
       "legendFormat": "{{job}} head series"
      }
     ]
    },
    {
     "title": "Head Chunks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_chunks{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", instance=~\"$instance\"}",
       "legendFormat": "{{job}} head chunks"
      }
     ]
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "rate(prometheus_engine_query_duration_seconds_count{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", instance=~\"$instance\", slice=\"inner_eval\"}[$__rate_interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Stage Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "max by (slice) (prometheus_engine_query_duration_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"${namespace}/prometheus\", instance=~\"$instance\", quantile=\"0.9\"}) * 1e3",
       "legendFormat": "{{slice}}"
      }
     ]
    }
   ]
  }
 ]
}